import { Card, CardContent } from "@/components/ui/card"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

export function FAQSection() {
  return (
    <div className="mt-12">
      <h2 className="mb-4 text-lg font-semibold" style={{ fontFamily: "'Playfair Display', serif" }}>
        Frequently Asked Questions
      </h2>
      <Card>
        <CardContent className="pt-4">
          <Accordion type="single" collapsible className="w-full">
            <AccordionItem value="item-1">
              <AccordionTrigger>
                What is image sonification?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  Image sonification is the process of converting visual
                  data from an image into audio. Each pixel's color and
                  position is mapped to specific audio frequencies and
                  characteristics, creating a unique sound representation of
                  the image.
                </p>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-2">
              <AccordionTrigger>
                What image formats are supported?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  We support common image formats including PNG, JPG/JPEG,
                  and WEBP. For best results, use images with clear contrast
                  and reasonable file sizes (under 10MB recommended).
                </p>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-3">
              <AccordionTrigger>
                Can I reconstruct any audio file to an image?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  No, only WAV files that were generated by this tool can be
                  reconstructed back to images. The audio file contains
                  specially encoded data that maps back to the original
                  image pixels.
                </p>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-4">
              <AccordionTrigger>
                Is my data stored on your servers?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  No, all processing happens locally in your browser. Your
                  images and audio files are never uploaded to any server.
                  This ensures complete privacy for your data.
                </p>
              </AccordionContent>
            </AccordionItem>
            <AccordionItem value="item-5">
              <AccordionTrigger>
                Why does my reconstructed image look different?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  The reconstruction process aims to be lossless, but some
                  minor variations may occur depending on the encoding
                  parameters used. For best results, use the same tool
                  version for both encoding and decoding.
                </p>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </CardContent>
      </Card>
    </div>
  )
}
