import { Card, CardContent } from "@/components/ui/card"
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion"

export function FAQSection() {
  return (
    <div className="mt-12">
      <h2 className="mb-4 text-lg font-semibold" style={{ fontFamily: "'Playfair Display', serif" }}>
        Frequently Asked Questions
      </h2>
      <Card>
        <CardContent className="pt-4">
          <Accordion type="single" collapsible className="w-full">
            <AccordionItem value="item-1">
              <AccordionTrigger>
                What is image sonification?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  Image sonification is the process of converting visual
                  data from an image into audio. Each pixel's color and
                  position is mapped to specific audio frequencies and
                  characteristics, creating a unique sound representation of
                  the image.
                </p>
              </AccordionContent>
            </AccordionItem>
            
            <AccordionItem value="item-2">
              <AccordionTrigger>
                How does file-to-image conversion work?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  File-to-image conversion encodes a file’s binary data into a PNG by mapping bytes to RGB pixels and embedding metadata like the original filename.
                  The image can be decoded to perfectly restore the original file.

                </p>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-3">
              <AccordionTrigger>
                What file types can be converted to images?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  Any file type can be converted documents, executables, archives, code, and more.
                   The process is fully lossless, so decoding returns the exact original file.

                </p>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-4">
              <AccordionTrigger>
                What image formats are supported?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  For sonification: PNG, JPG/JPEG, and WEBP formats. 
                  For file-to-image: output is always PNG for lossless encoding. 
                  Best results with images under 10MB.
                </p>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-5">
              <AccordionTrigger>
                Can I decode any PNG image back to a file?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  No, only PNG images created using our File→Image converter can be decoded. 
                  These contain special identification data. Regular photos won't work 
                  for file reconstruction.
                </p>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-6">
              <AccordionTrigger>
                Can I reconstruct any audio file to an image?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  No, only WAV files that were generated by this tool can be
                  reconstructed back to images. The audio file contains
                  specially encoded data that maps back to the original
                  image pixels.
                </p>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-7">
              <AccordionTrigger>
                Is my data stored on your servers?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  No, all processing happens locally in your browser. Your files are never 
                  uploaded to any server. This ensures complete privacy for your data, 
                  whether converting images to sound or files to images.
                </p>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-8">
              <AccordionTrigger>
                What are some use cases for file-to-image conversion?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  Useful for: storing files in image-only platforms, creating visual backups, 
                  sharing files through image channels, data art projects, or representing 
                  digital information visually.
                </p>
              </AccordionContent>
            </AccordionItem>

            <AccordionItem value="item-9">
              <AccordionTrigger>
                Why does my reconstructed image look different?
              </AccordionTrigger>
              <AccordionContent>
                <p className="text-muted-foreground">
                  The reconstruction process aims to be lossless, but some
                  minor variations may occur depending on the encoding
                  parameters used. For best results, use the same tool
                  version for both encoding and decoding.
                </p>
              </AccordionContent>
            </AccordionItem>
          </Accordion>
        </CardContent>
      </Card>
    </div>
  )
}
